- deploy/multiple-container/docker-compose.yml
Issue fix for reporting containers went unhealthy issue
> Docker Health Check Issue Fix

- deploy/multiple-container/docker-compose.yml
> Release 4.1.78 

- deploy/multiple-container/docker-compose.yml
Bold Reports 4.2.52 release image name changes
> 4.2.52 release image changes

- deploy/multiple-container/docker-compose.yml
Bold Reports 4.2.52 release image name changes
> 4.2 release image changes

- README.md
- deploy/multiple-container/docker-compose.yml
Update docker documentation application startup in backend using environment variables.
> Report-17541 :Update docker documentation

- README.md
- deploy/multiple-container/docker-compose.yml
Application startup in backend using environment vaiables
> 17541 update docker docs

- README.md
Included the License and prerequisites section.
> License and Prerequisites Changes

- README.md
> Update Hardware Requirements

- README.md
Update deployment prerequisites
> Update deployment prerequisites

- README.md
Update deployment prerequisites and Environment variables
> Update docker documentation

- README.md
- deploy/multiple-container/docker-compose.yml
- docs/multiple-container.md
- release image changes
- image tag changes
> 4.2.78 sp release changes

- README.md
- deploy/multiple-container/docker-compose.yml
- docs/multiple-container.md
- I have added the SP 2 release changes
> Updated the SP 2 release changes

- README.md
- docs/multiple-container-podman.md
document for deploy boldreports application using podman.
> REPORT-21195: Added steps to deploy boldreports using podman

- README.md
- deploy/multiple-container/default.conf
- deploy/multiple-container/docker-compose.yml
- deploy/single-container/docker-compose.yml
- docs/multiple-container-podman.md
- docs/multiple-container.md
- docs/single-container.md
- docs/upgrade.md
- Upgrade.md changes
- Single docker container changes.
- Release image changes
> Release 5.1 Changes

- README.md
Updated the release image version.
> Old version changes

- docs/FAQ/how-to-configure-ssl-for-docker-compose.md
Updated correct image link in the documentation.
> 475229 - Updated image link in the document

- deploy/multiple-container/docker-compose.yml
- docs/multiple-container-podman.md
- docs/multiple-container.md
Added the volume path changes in the multpile container and podman ms files
> volumes path changes

- README.md
- deploy/multiple-container/docker-compose.yml
- docs/multiple-container-podman.md
- docs/multiple-container.md
- docs/upgrade.md
Image tag and release repo changes
> 5.2 refresh release changes

- README.md
- deploy/multiple-container/docker-compose.yml
- docs/multiple-container-podman.md
- docs/multiple-container.md
- docs/upgrade.md
- V5.3 Release image changes.
- Branch name changes.
> V5.3 release changes

- README.md
Release date changes included in readme file.
> V5.3 Release Date Changes.

- README.md
- docs/how-to-deploy-bold-reports-and-configure-startup-manually.md
- docs/how-to-deploy-bold-reports-using-existing-db-server.md
Need to correct the command for downloading the docker compose file.
> Changes in downloading docker compose file

- README.md
- deploy/multiple-container/docker-compose.yml
- docs/FAQ/how-to-auto-deploy-bold-reports-multiple-services-in-docker-compose.md
- docs/how-to-use-host-path-as-persistent-volume-for-bold-reports-deployment.md
- docs/multiple-container-podman.md
- docs/multiple-container.md
- docs/upgrade.md
v5.4.30 Release changes to master branch
> v5.4.30 Docker deployment and documentation changes

- deploy/docker-swarm/multiple-container/default.conf
- deploy/docker-swarm/multiple-container/docker-compose.yml
- deploy/docker-swarm/single-container/docker-compose.yml
Provided the Docker Swarm Report Server Deployment Support like Bold BI for both Multiple and Single Container 
BI Docker Swarm Repository - https://github.com/boldbi/boldbi-docker/tree/main/deploy/docker-swarm
> Docker Swarm Report Server Deployment Support

- README.md
- deploy/docker-swarm/multiple-container/docker-compose.yml
- deploy/multiple-container/docker-compose.yml
- docs/FAQ/how-to-auto-deploy-bold-reports-multiple-services-in-docker-compose.md
- docs/how-to-use-host-path-as-persistent-volume-for-bold-reports-deployment.md
- docs/multiple-container-podman.md
- docs/multiple-container.md
- docs/upgrade.md
Added version changes in the documentation.
> Changing version to 6.1.45

- README.md
- deploy/docker-swarm/multiple-container/docker-compose.yml
- deploy/multiple-container/docker-compose.yml
- docs/FAQ/how-to-auto-deploy-bold-reports-multiple-services-in-docker-compose.md
- docs/how-to-use-host-path-as-persistent-volume-for-bold-reports-deployment.md
- docs/multiple-container-podman.md
- docs/multiple-container.md
- docs/upgrade.md
Included the changes to upgrade to version 6.2.32 in docker environment.
> Changing version to 6.2.32

- README.md
- deploy/docker-swarm/multiple-container/default.conf
- deploy/docker-swarm/multiple-container/docker-compose.yml
- deploy/multiple-container/default.conf
- deploy/multiple-container/docker-compose.yml
- deploy/single-container-eval-no-license/docker-compose.yml
- deploy/single-container-eval/docker-compose.yaml
- docs/how-to-use-host-path-as-persistent-volume-for-bold-reports-deployment.md
- docs/multiple-container-podman.md
- docs/multiple-container.md
- docs/upgrade.md
Added changes for V10.1 release
> Added changes for V10.1 release 

- README.md
- deploy/docker-swarm/multiple-container/docker-compose.yml
- deploy/multiple-container/docker-compose.yml
- deploy/single-container-eval-no-license/docker-compose.yml
- deploy/single-container-eval/docker-compose.yaml
- docs/how-to-use-host-path-as-persistent-volume-for-bold-reports-deployment.md
- docs/multiple-container-podman.md
- docs/multiple-container.md
- docs/upgrade.md
In PR i was added v11.1 rollout files
> Added v11.1.10 rollout files
